#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int difficulty_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int SPDifficulty = 2131099684;
			
			// aapt resource value: 0x7f060002
			public const int btnA = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btnB = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnC = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btnD = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnE = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int btnF = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int btnG = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btnH = 2131099658;
			
			// aapt resource value: 0x7f060022
			public const int btnHighScores = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int btnI = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnJ = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int btnK = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnL = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int btnM = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int btnN = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int btnO = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int btnP = 2131099667;
			
			// aapt resource value: 0x7f060021
			public const int btnPlay = 2131099681;
			
			// aapt resource value: 0x7f060014
			public const int btnQ = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int btnR = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int btnS = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int btnT = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int btnU = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int btnV = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnW = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btnX = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int btnY = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnZ = 2131099679;
			
			// aapt resource value: 0x7f060023
			public const int button3 = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int imageView = 2131099648;
			
			// aapt resource value: 0x7f060020
			public const int imageView1 = 2131099680;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout2 = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout3 = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout4 = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout5 = 2131099677;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int difficulty_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
